
export const ASCII_ICONS = {
  skull: '☠',
  eye: '◉',
  eyes: '◉◉',
  warning: '⚠',
  check: '✓',
  cross: '✗',
  bullet: '►',
  arrow: '→',
  arrowLeft: '◄',
  danger: '☢',
  bio: '☣',
  electric: '⚡',
  death: '†',
  moon: '☽',
  pentagram: '⛤',
  psi: 'Ψ',
  omega: 'Ω',
  delta: 'Δ',
  infinity: '∞',
  target: '⊕',
  scan: '◎',
  signal: '◈',
  lock: '⊠',
  unlock: '⊡',
  gear: '⚙',
  rec: '●',
  star: '★',
  heart: '♥',
  music: '♫',
  divider: '═══════════════════',
  glitch: '▓░▒█',
} as const;

export type IconKey = keyof typeof ASCII_ICONS;
